[platformio] ; глобальные параметры
description = "Hello World Examle"

[env]
platform = native ; ПО хост-компьютера 
build_flags = -O0
    -std=c11 ; Стандарт C11
    -Wall    ; Вывод всех предупрежденний компилятора
[env:helloworld]    ; окружение для программы hellp word
debug_test = native/test_dynlist
build_type = debug ; включить символы отладки
build_src_filter = +<helloworld/*.c> ; папка с исходными кодами /src/helloworld
test_framework = custom
check_tool = cppcheck
check_flags = cppcheck:--enable=all
    --suppress=unusedFunction
    --suppress=unmatchedSuppression
check_src_filters =
    +<src/helloworld/*.c>
    +<lib/dynlist/src/*.c>